Alumni/urls.py
from django.urls import path
from . import views
from . import Lviews

urlpatterns =[
	path('Alumi-list/',views.LisAlumi, name='ALm'),
	path('Adisiona-Alumni/', views.AddAlmni, name='a-alm'),
	path('List-Det/AlumiDet/<int:id>/', views.AlumiDet, name='Det_ALm' ),
	path('Hamos-List/hamosAlm/<int:id>/', views.hamosAlm, name='H-ALM'),
	path('Exporta-Dadus-Alumni.html/', views.export_alumni_csv, name='e-csv'),
	path('Importa-Dadus-Alumni.html/', views.import_alumni, name='i-file'),
	path('Hamos-Dadus-Alimni.html/<str:pk>/', views.soft_delete, name='sof-delete'),

	#filterMun
	path('Lista-Alumni-Munisipiu.html/<str:pk>/', Lviews.alimnimun, name='ald-mun'),
	path('Lista-Alumni-Feto-Munisipiu/<str:pk>/', Lviews.alimnifmun, name='falm-mun'),
	path('Lista-Alumni-Munisipiu-All/<str:pk>', Lviews.alimnimunall, name='all-mun'),
	path('Lista-Alumni-Munisipiu-Tinan/<str:pk>/', Lviews.alm_mun, name='all-tinan-mun'),

	path('Lista-Alumni-Ano.html/<str:pk>/',Lviews.alumni_ano, name='Lista-Ano-mun'),
	path('Lista-HadiaAlumni.html/<str:pk>/', views.HadiaAlumni, name='Hadia-Alumi'),


	# lista Pesoal ALumni
	path('Lista-AlumniPesoal.html/', views.lista_pes_alumni, name='Lista-pesoal-alumni'),
	path('Importa-Dadus-Alumni-Excel.html/', views.import_alumni_excel, name='excel-import'),
	path('Altera-Dadus-Pessoal/<str:hashid>/', views.edit_my_edintity, name='edit-my-data')


]

Si_Alumni/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from Main import views as main_views
from django.contrib.auth import views as auth_views
from django.conf.urls import handler404, handler500

admin.site.site_title ='SI-ALUMNI-UNTL'
admin.site.site_header ='SI-ALUMNI-UNTL'
admin.site.index_title ='SI-ALUMNI-UNTL'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', main_views.home, name='home'),
    path('Admin-Page/', main_views.index, name='index'),
    path('Home-Page/', include('Informasaun.urls')),
    path('Login.html/', auth_views.LoginView.as_view(template_name='Home/login.html'), name='login'),
    path('Logout.html/', main_views.LoginView, name='logout'),

    #Api
    path('API/Report/', include('report.Api.urls')),
    path('Ajax/', include('Costum.urls')),

    # Lista Sira
    path('Alumi-list/', include('Alumni.urls')),
    path('Dosen-list/', include('Docente.urls')),
    path('Dep-List/', include('Departamento.urls')),
    path('Fac-List/', include('Faculdade.urls')),
    path('Act-List/', include('Activity.urls')),
    path('Account/', include('User.urls'))

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

User/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('Pajina-Utilizador-Alumni.html/', views.Alumni_user, name='Au-list'),
    path('account/', views.AccountUpdate, name='user-account'),
    path('change/password/', views.UserPasswordChangeView.as_view(), name='user-change-password'),
    path('change/password/done/', views.UserPasswordChangeDoneView.as_view(), name='user-change-password-done'),
    path('User-UserAlumi.html/', views.perfilUser, name='Perfil'),
]

Costum/models.py
from django.db import models

# Create your models here.
class Municipality(models.Model):
	code = models.CharField(max_length=50, verbose_name='Sigla')
	name = models.CharField(max_length=50, verbose_name='Naran Munisipiu', null=False)

	def __str__(self):
		template = '{0.name}'
		return template.format(self)

class AdministrativePost(models.Model):
	municipality = models.ForeignKey(Municipality, on_delete=models.CASCADE, verbose_name='Munisipiu')
	name = models.CharField(max_length=50, verbose_name='Naran Postu', null=False)

	def __str__(self):
		template = '{0.name}'
		return template.format(self)

class Village(models.Model):
	administrativePost = models.ForeignKey(AdministrativePost, on_delete=models.CASCADE, verbose_name='Postu')
	name = models.CharField(max_length=50, verbose_name='Naran Suku', null=False)

	def __str__(self):
		template = '{0.name}'
		return template.format(self)

class SubVillage(models.Model):
	village  = models.ForeignKey(Village, on_delete=models.CASCADE, verbose_name='Suku')
	name = models.CharField(max_length=50, verbose_name='Naran Aldeia', null=False)

	def __str__(self):
		template = '{0.name}'
		return template.format(self)

class Pozisaun(models.Model):
	name = models.CharField(max_length=50, verbose_name='Naran Pozisaun')

	def __str__(self):
		template = '{0.name}'
		return template.format(self)


class Nasaun(models.Model):
	name = models.CharField(max_length=50, verbose_name='Naran Nasaun', null=False)

	def __str__(self):
		template = '{0.name}'
		return template.format(self)


class Relijiaun(models.Model):
	name = models.CharField(max_length=50, verbose_name='Naran Relijiaun', null=False)

	def __str__(self):
		template = '{0.name}'
		return template.format(self)

class Year(models.Model):
	name = models.CharField(max_length=50, verbose_name='Tinan', null=False)

	def __str__(self):
		template = '{0.name}'
		return template.format(self)

class Instituisaun(models.Model):
	code = models.CharField(max_length=50, verbose_name='Sigla')
	name = models.CharField(max_length=50, verbose_name='Naran', null=False)

	def __str__(self):
		template = '{0.name}'
		return template.format(self)

class Diresaun(models.Model):
	instuisaun = models.ForeignKey(Instituisaun, on_delete=models.CASCADE, null=True, verbose_name='Instituisaun')
	name = models.CharField(max_length=50, verbose_name='Naran', null=False)

	def __str__(self):
		template = '{0.name}'
		return template.format(self)

class nivelmaster(models.Model):
	code = models.CharField(max_length=50, verbose_name='Sigla')
	name = models.CharField(max_length=50, verbose_name='Naran', null=False)

	def __str__(self):
		template = '{0.name}'
		return template.format(self)

Alumni/views.py
from django.shortcuts import render, get_object_or_404, redirect
from Costum.models import *
from Alumni.models import *
from django.core.paginator import Paginator
from Faculdade.models import Faculdade
from django.db.models import Count
from django.http import JsonResponse
from django.db.models import Q
from django.utils.timezone import now
from django.contrib.auth.decorators import login_required
from .forms import *
from django.contrib import messages
from User.decorators import allowed_users
from Main.utils import *
from django.contrib.auth.models import User, Group
from django.contrib.auth.hashers import make_password
from django.http import HttpResponse
import pandas as pd
import csv, io
from tablib import Dataset
from Alumni.resource import AlumnisResources
from datetime import datetime 

@login_required
@allowed_users(allowed_roles=['Admin','Vice_Reitor','Staff'])
def LisAlumi(request):
    group = request.user.groups.all()[0].name
    objects = Alumni.objects.filter(is_active=True).all().order_by('-id')
    ano  = Year.objects.all()
    context ={
		'page':'Alumi',
		'objects':objects,
		'title':'Lista Alumni',
		'legend':'Lista Alumni',
        'group':group,'ano':ano
	}
    return render(request, 'Alumi/Lista_alumi.html', context)


@login_required
@allowed_users(allowed_roles=['Admin','Vice_Reitor','Staff'])
def AddAlmni(request):
    u_group = Group.objects.get(name='Alumni')
    if request.method == 'POST':
        form = AlumniForm(request.POST, request.FILES)
        if form.is_valid():
            instance = form.save(commit=False)
            instance.create_by = request.user
            instance.create_at = now().date()
            newid = getjustnewid(Alumni)
            get_newId = hash_md5(newid)
            instance.hashid = get_newId
            instance.save()
            password = make_password('Password') 
            user = User.objects.create(username=instance.nre, password=password)
            user.groups.add(u_group)
            user.save()
            obj1 = Alumniuser.objects.create(alumni=instance, user=user)
            obj1.save()
            messages.success(request, f'Dadus Alumni {instance.name} rai ona ho Susesu')
            return redirect('ALm') 
        else:
        	messages.error(request, f'Falla Adisiona Dadus Alumni Foun')
    else:
        form = AlumniForm()
    context={
    	'page':'Addalumi',
    	'title':'Lista Adisiona Alumni',
        'legend':'Adisiona Dadus Alumni',
    	'form':form,
    }
    return render(request, 'Alumi/form.html', context)




@login_required
@allowed_users(allowed_roles=['Admin', 'Vice_Reitor', 'Staff'])
def HadiaAlumni(request, pk):
    instance = get_object_or_404(Alumni, pk=pk)
    if request.method == 'POST':
        form = AlumniForm(request.POST, request.FILES, instance=instance)
        if form.is_valid():
            alumni = form.save(commit=False)
            alumni.save()
            messages.success(request, f'Dadus Alumni ho naran {alumni.name} haian ona ho sussesu.')
            return redirect('ALm')  
        else:
            messages.error(request, f'Dadus Alumni ho naran {instance.name} sei failha.')
    else:
        form = AlumniForm(instance=instance)

    context = {
        'page': 'Edit Alumni',
        'title': 'Hadia Dadus Alumni',
        'legend': 'Hadia Dadus Alumni',
        'form': form,
    }
    return render(request, 'Alumi/HadiForm.html', context)



def AlumiDet(request, id):
    objec= get_object_or_404( Alumni, id=id)
    context ={
        'objec':objec,
        'title':'Lista Detailu Alumni',
        'legend':f'Detaillu Dadus Alumni {objec.name}'
    }
    return render(request,'Alumi/Detailu.html', context)


def hamosAlm(request, id):
    hamos = get_object_or_404(Alumni, id=id)
    name = hamos.name 
    hamos.delete()
    messages.success(request, f'Lista name ho {name} hamos ona ho Susesu.')
    return redirect('ALm')

def export_alumni_csv(request):
    response = HttpResponse(content_type='text/csv')
    response['Content-Disposition'] = 'attachment; filename="alumni.csv"'
    writer = csv.writer(response)
    writer.writerow(['NRE', 'Naran Kompletu', 'Sexu','faculdade', 'Departamento','Fatin Moris', 'Data Moris', 'Email','Municipio','Posto','Suku','Aldeia','Tina Hahu','Tinan Remata','Orientador I',\
        'Orientador II','Title','Point','Predikadu Final','Naran Aman','Naran Inan','Email','Hela Fafin Inan Aman']) 
    for alumni in Alumni.objects.all():
        writer.writerow([alumni.nre, alumni.name, alumni.sex,alumni.faculdade, alumni.departamento, alumni.pob, alumni.dob, alumni.email,\
          alumni.mun,alumni.post, alumni.suk, alumni.ald, alumni.start_date, alumni.end_date,\
          alumni.orientadorI,alumni.orientadorII, alumni.title, alumni.point, alumni.predict, alumni.fname, alumni.mname, alumni.email, alumni.paddres])
    return response


def import_alumni(request):
    if request.method == 'POST':
        form = UploadFileForm(request.POST, request.FILES)
        if form.is_valid():
            dataset = Dataset()
            new_file = request.FILES['file']
            try:
                imported_data = dataset.load(new_file.read(), format='xlsx')
                resource = AlumnisResources()
                result = resource.import_data(dataset, dry_run=True)  # Faze Test 

                if not result.has_errors():
                    resource.import_data(dataset, dry_run=False)  # rai ba DB
                    messages.success(request, "Dadus Alumni Rai ona ho Susesu.")
                    return redirect('ALm')  
                else:
                    messages.error(request, "Akontese Error Wainhira rai Dadus.")
            except Exception as e:
                messages.error(request, f"Error: {str(e)}")

    else:
        form = UploadFileForm()
    context = {
        'title': 'Import Dadus Alumni',
        'legend': 'Import Dadus Alumni',
        'form':form
    }
    return render(request, 'Alumi/import_form.html', context)

def import_alumni_excel(request):
    if request.method == 'POST':
        form = UploadExcelForm(request.POST, request.FILES)
        if form.is_valid():
            excel_file = request.FILES['file']
            df = pd.read_excel(excel_file)
            for index, row in df.iterrows():
                try:
                    Alumni.objects.create(
                        NRE=row['nre'],
                        Naran_Kompletu=row['name'],
                        Sexu=row['sex'],
                        Data_Moris=row['dob'],
                        Fatin_Moris=row['pob'],
                        faculdade=Faculdade.objects.get(name=row['faculdade']) if pd.notna(row['faculdade']) else None,
                        Departamento=Departamento.objects.get(name=row['departamento']) if pd.notna(row['departamento']) else None,
                        mun=Municipality.objects.get(name=row['mun']) if pd.notna(row['mun']) else None,
                        Postu=AdministrativePost.objects.get(name=row['post']) if pd.notna(row['post']) else None,
                        Suku=Village.objects.get(name=row['suk']) if pd.notna(row['suk']) else None,
                        Aldeia=SubVillage.objects.get(name=row['ald']) if pd.notna(row['ald']) else None,
                        Tinan_Hahu=Year.objects.get(tinan=row['start_date']) if pd.notna(row['start_date']) else None,
                        Tinan_Remata=Year.objects.get(tinan=row['end_date']) if pd.notna(row['end_date']) else None,
                        create_by=User.objects.get(username=row['create_by']) if pd.notna(row['create_by']) else request.user,
                        Orientador_I=Docente.objects.get(name=row['orientadorI']) if pd.notna(row['orientadorI']) else None,
                        Orientador_II=Docente.objects.get(name=row['orientadorII']) if pd.notna(row['orientadorII']) else None,
                        Title=row['title'] if pd.notna(row['title']) else '',
                        Point=row['point'] if pd.notna(row['point']) else None,
                        Predikadu=row['predict'] if pd.notna(row['predict']) else '',
                        name_Aman=row['fname'] if pd.notna(row['fname']) else '',
                        name_Inan=row['mname'] if pd.notna(row['mname']) else '',
                        Email=row['email'] if pd.notna(row['email']) else '',
                        Hela_Fafin_Inan_Aman=row['paddres'] if pd.notna(row['paddres']) else '',
                        hashid='-',  
                    )
                except Exception as e:
                    messages.error(request, f"Falha Importa Dadus-{index+2}: {e}")
                    continue
            messages.success(request, "Dadus Alumni Adisiona ho Susesu.")
            return redirect('ALm')
    else:
        form = UploadExcelForm()
    return render(request, 'Alumi/import_form.html', {'form': form})


@login_required
@allowed_users(allowed_roles=['Admin'])
def soft_delete(request, pk):
    try:
        objects = get_object_or_404(Alumni, pk=pk)
        objects.is_active=False
        objects.save()
        messages.success(request, f'Ita Ho Susesu Hamos Ona Dadus {objects.name}')
        return redirect('ALm')
    except:
        messages.error(request, f'Falha Atu Hamos Dadus {objects.name}')
        return redirect('ALm')



@login_required
@allowed_users(allowed_roles=['Alumni', 'Admin'])
def lista_pes_alumni(request):
    user = request.user
    try:
        alumni_list = Alumniuser.objects.get(user=user)
        lumni = alumni_list.alumni
    except Alumni.DoesNotExist:
        alumni = None
    context = {
        'legend': f'Lista Alumni Pessoal - ({user.username})',
        'title': 'Dadus Pessoal Alumni',
        'lumni':lumni 
    }
    return render(request, 'Alumi/DetailuPesoal.html', context)

@login_required
@allowed_users(allowed_roles=['Admin','Alumni'])
def edit_my_edintity(request, hashid):
    data = get_object_or_404(Alumni, hashid=hashid)

Alumni/templates/Alumi/Detailu.html
{% extends 'Main/Admin/layout.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}

<div class="container mt-5">
    <nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="{% url 'index' %}">Home</a></li>
    <li class="breadcrumb-item"><a href="{% url 'ALm' %}"></i>Lista Alumni</a></li>
    <li class="breadcrumb-item active" aria-current="page">{{legend|upper}}</li>
  </ol>
</nav>
    <div class="row">
        <!-- Table Content -->
        <div class="col-12 col-md-6 col-lg-12">
            <div class="card rounded">
                <div class="card-header bg-primary">
                    <h6 class="font-weight-bold text-white"><i class="fa fa-list"></i> {{legend|upper}}</h6>
                </div>
                <div class="card-body">
                    {% if messages %}
                        {% for message in messages  %}
                            <div class="alert alert-{{message.tags}}">{{message}}</div>
                        {% endfor %}
                    {% endif %}

                <div class="row">
                <div class="col-md-4 mb-4">
                  <div class="card">
                    <div class="card-header">
                      <h6>
                        <i class="fa fa-camera"></i> Image
                      </h6>
                    </div>
                    <div class="card-body text-center">
                      {% if objec.foto %}
                        <img src="{{ objec.foto.url }}" alt="Foto Alumni" class="img-circle" width="100%" height="200px">
                      {% else %}
                        <img src="{% static 'image/UNTL.png' %}" alt="Foto Alumni" class="rounded" width="100%">
                      {% endif %}
                    </div>
                  </div>
                </div>
                <div class="col-md-8 mb-4">
                  <div class="card">
                    <div class="card-header">
                      <h6><i class="fa fa-user"></i> Dadus Pessoal</h6>
                    </div>
                    <div class="card-body">
                      <table class="table table-borderles table-sm" width="100%">
                    <tr>
                      <th>Nu Rejistu Estudante</th>
                      <td>: {{ objec.nre }}</td>
                    </tr>
                     <tr>
                      <th>Naran</th>
                      <td>: {{ objec.name }}</td>
                    </tr>
                    <tr>
                      <th>Sexu</th>
                      <td>: {{ objec.sex }}</td>
                    </tr>
                    <tr>
                      <th>Data Moris</th>
                      <td>: {{ objec.dob }}</td>
                    </tr>
                    <tr>
                      <th>Fatin Moris</th>
                      <td>: {{ objec.pob }}</td>
                    </tr>
                  </table>
                    </div>
                  </div>
                </div>
                <div class="col-md-8 mb-4">
                  <div class="card">
                    <div class="card-header">
                      <h6><i class="fa fa-eye"></i> Informasaun Escola</h6>
                    </div>
                    <div class="card-body">
                      <table class="table table-borderles table-sm" width="100%">
                    <tr>
                      <th>Faculdade</th>
                      <td>: {{ objec.faculdade}}</td>
                    </tr>
                    <tr>
                      <th>Departamento</th>
                      <td>: {{ objec.departamento }}</td>
                    </tr>
                     <tr>
                      <th>Tinan Hahu</th>
                      <td>: {{ objec.start_date }}</td>
                    </tr>
                    <tr>
                      <th>Tinan Remata</th>
                      <td>: {{ objec.start_date }}</td>
                    </tr>
                    <tr>
                      <th>Data Rejistu</th>
                      <td>: {{ objec.create_at }}</td>
                    </tr>
                    <tr>
                      <th>Rejistu Husi</th>
                      <td>: {{ objec.create_by }}</td>
                    </tr>
                    <tr>
                      <th>Orientador I</th>
                      <td>: {{ objec.orientador}}</td>
                    </tr>
                    <tr>
                      <th>Orientador II</th>
                      <td>: {{ objec.orientador }}</td>
                    </tr>
                    <tr>
                      <th>Titulo Teze</th>
                      <td>: {{ objec.title }}</td>
                    </tr>
                    <tr>
                      <th>Valor Teze</th>
                      <td>: {{ objec.point }}</td>
                    </tr>
                    <tr>
                      <th>Predikadu Final</th>
                      <td>: {{ objec.predict }}</td>
                    </tr>
              </table>
                    </div>
                  </div>
                </div>
            <div class="col-md-4">
                  <div class="card">
                    <div class="card-header">
                      <h6><i class="fa fa-list"></i> Enderesu</h6>
                    </div>
                    <div class="card-body">
                      <table class="table table-borderles table-sm" width="100%">
                    <tr>
                      <th>Munisipiu</th>
                      <td>: {{ objec.mun }}</td>
                    </tr>
                    <tr>
                      <th>Postu</th>
                      <td>: {{ objec.post }}</td>
                    </tr>
                    <tr>
                      <th>Suku</th>
                      <td>: {{ objec.suk }}</td>
                    </tr>
                    <tr>
                      <th>Aldeia</th>
                      <td>: {{ objec.ald }}</td>
                    </tr>
                   
                    <tr>
                      <th>Naran Aman</th>
                      <td>: {{ objec.fname }}</td>
                    </tr>
                    <tr>
                      <th>Naran Inan</th>
                      <td>: {{ objec.mname }}</td>
                    </tr>
                    <tr>
                      <th>Nu Kontaktu</th>
                      <td>: {{ objec.Tpone }}</td>
                    </tr>
                    <tr>
                      <th>Email</th>
                      <td>:{{ objec.email }}</td>
                    </tr>
                    <tr>
                      <th>Enderesu Inan Aman</th>
                      <td>: {{ objec.paddres }}</td>
                    </tr>
                  </table>
                    </div>
                  </div>
                </div>
                      <a href="{% url 'ALm' %}"class="btn btn-danger"><i class="fa fa-arrow-left"></i>Fila</a>      
                </div>
            </div>
        </div> <!-- end content col -->
    </div> <!-- end row -->
</div> <!-- end container -->
{% endblock %}

Alumni/templates/Alumi/HadiForm.html
{% extends 'Main/Admin/layout.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}

<div class="container mt-5">
    <nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="#">Home</a></li>
    <li class="breadcrumb-item"><a href="{% url 'ALm' %}">Lista Alumni</a></li>
    <li class="breadcrumb-item active" aria-current="page">{{legend|upper}}</li>
  </ol>
</nav>
    <div class="row">
        <!-- Table Content -->
        <div class="col-12 col-md-6 col-lg-12">
            <div class="card rounded">
                <div class="card-header bg-primary">
                    <h6 class="font-weight-bold text-white"><i class="fa fa-list"></i> {{legend|upper}}</h6>
                </div>
                <div class="card-body">
                        <form method="post" id="AlmuniForm" enctype="multipart/form-data" data-postu-url="{% url 'ajax-load-postu' %}" data-suku-url="ajax-load-suku" data-aldeia-url="ajax-load-aldeia" novalidate>

                            {% csrf_token %}
                            {% crispy form %}
                        </form>
                        <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
                        <script type="text/javascript">
                            $("#id_municipality").change(function() {
                                var url = $("#AlmuniForm").attr("data-postu-url");
                                var municipalityId = $(this).val();

                                $.ajax({
                                    url: url,
                                    data: {
                                        'municipalityId': municipalityId
                                    },
                                    success: function(data) {
                                        $("#id_administrativepost").html(data);
                                    }
                                });
                            });

                            $("#id_administrativepost").change(function() {
                                var url = $("#AlmuniForm").attr("data-suku-url");
                                var administrativePostId = $(this).val();

                                $.ajax({
                                    url: url,
                                    data: {
                                        'administrativePostId': administrativePostId
                                    },
                                    success: function(data) {
                                        $("#id_village").html(data); 
                                    }
                                });
                            });
                        </script>

                </div>
            </div>
        </div> <!-- end content col -->
    </div> <!-- end row -->
</div> <!-- end container -->
{% endblock %}

Alumni/templates/Alumi/form.html
{% extends 'Main/Admin/layout.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}

<div class="container mt-5">
    <nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="#">Home</a></li>
    <li class="breadcrumb-item"><a href="{% url 'ALm' %}">Lista Alumni</a></li>
    <li class="breadcrumb-item active" aria-current="page">{{legend|upper}}</li>
  </ol>
</nav>
    <div class="row">
        <!-- Table Content -->
        <div class="col-12 col-md-6 col-lg-12">
            <div class="card rounded">
                <div class="card-header"  style="background: #41d5f0;">
                    <h6 class="font-weight-bold text-white"><i class="fa fa-list"></i> {{legend|upper}}</h6>
                </div>
                <div class="card-body">
                        <form method="post" id="AlmuniForm" enctype="multipart/form-data" data-postu-url="{% url 'ajax-load-postu' %}" data-suku-url="ajax-load-suku" data-aldeia-url="ajax-load-aldeia" novalidate>

                            {% csrf_token %}
                            {% crispy form %}
                        </form>
                        <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
                        <script type="text/javascript">
                            $("#id_municipality").change(function() {
                                var url = $("#AlmuniForm").attr("data-postu-url");
                                var municipalityId = $(this).val();

                                $.ajax({
                                    url: url,
                                    data: {
                                        'municipalityId': municipalityId
                                    },
                                    success: function(data) {
                                        $("#id_administrativepost").html(data);
                                    }
                                });
                            });

                            $("#id_administrativepost").change(function() {
                                var url = $("#AlmuniForm").attr("data-suku-url");
                                var administrativePostId = $(this).val();

                                $.ajax({
                                    url: url,
                                    data: {
                                        'administrativePostId': administrativePostId
                                    },
                                    success: function(data) {
                                        $("#id_village").html(data); 
                                    }
                                });
                            });
                        </script>

                </div>
            </div>
        </div> <!-- end content col -->
    </div> <!-- end row -->
</div> <!-- end container -->
{% endblock %}

Alumni/templates/Alumi/import_form.html
{% extends 'Main/Admin/layout.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}

<div class="container mt-5">
    <nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="#">Home</a></li>
    <li class="breadcrumb-item"><a href="{% url 'ALm' %}">Lista Alumni</a></li>
    <li class="breadcrumb-item active" aria-current="page">{{legend|upper}}</li>
  </ol>
</nav>
    <div class="row">
        <!-- Table Content -->
        <div class="col-12 col-md-6 col-lg-12">
            <div class="card rounded">
                <div class="card-header" style="background: #41d5f0;">
                    <h6 class="font-weight-bold text-white"><i class="fa fa-list"></i> {{legend|upper}}</h6>
                </div>
                <div class="card-body">
                    <h2>Import Data Alumni dari Excel</h2>
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form.as_p }}
                <button type="submit" class="btn btn-outline-success"><i class="fa fa-save"></i> Import</button>
                    </form>
                </div>
            </div>
        </div> <!-- end content col -->
    </div> <!-- end row -->
</div> <!-- end container -->
{% endblock %}